stlink-org/stlink

flash/main.c
Previous commit changed binary "flash" to "st-flash" but the actual
code printed help message still called it "flash". This commit changes
it to "st-flash".
=> change flash to st-flash

gdbserver/gdb-server.c, src/stlink-common.h
STM32_CHIPID_F4_HD (as on STM32F429I-Discovery board) has more RAM than STM32_CHIPID_F4; we need to distinguish the two so that the debugger can see the top third of RAM on the STM32F429I-Discovery.
See [Issue 287](https://github.com/texane/stlink/issues/287).
=> STM32F42xx memory map issues

src/stlink-sg.c
Hi,
I've faced multiple error messages while still using compiled tools successfully. This was confusing. Those errors were thrown to stderr twice by stlinkv1 specific functions while stlinkv2 was used. I've removed duplicated error message and replaced the other one with logging macro for consistency with the rest of logs in this file. If additional device opening error needs to be thrown I think it's up to 'stlink_v1_open' and 'stlink_open_usb' callers to log it if both calls fail.
Just letting you know if you're interested.
Regards.
=> Minor error reporting tweaks and redundant  includes removal

gdbserver/gdb-server.c, mingw/mingw.c, mingw/mingw.h
On Windows after GDB disconnect:
2015-03-15T18:06:19 INFO gdbserver/gdb-server.c: Listening at *:4242...
2015-03-15T18:06:37 INFO gdbserver/gdb-server.c: GDB connected.
2015-03-15T18:06:47 ERROR gdbserver/gdb-server.c: cannot recv: -2
2015-03-15T18:06:47 INFO gdbserver/gdb-server.c: Listening at *:4242...
We cannot connect again cause our first forgotten socket is still listening the port.
=> Properly close socket on WIN32 to allow accepting further connections

README
I have tested this using several custom boards mainly with the standalone STLinkV2 and some AliExpress STLink-ish sticks (which act like the standalong STLinkV2). There have been no problems whatsoever with st-flash / st-util
=> Added STM32F030F4P6 to working targets

gdbserver/gdb-server.c
The length field for internal sram size looks to be incorrect - it should be 256K. The stm32f429xxx/439xxx literature says "up to 256K" but I cant find an active chip in that range that has anything other than 256K [link](http://www.st.com/web/en/catalog/mmc/FM141/SC1169/SS1577/LN1806?ecmp=stm32f429-439_pron_pr-ces2014_nov2013&sc=stm32f429-439-pr).
Also added the FMC memory map according to the [reference manual](http://www.st.com/stonline/stappl/resourceSelector/app?page=fullResourceSelector&doctype=reference_manual&LineID=1806) (page 1586), and I can now access external memory from within GDB. Admittedly, I've only tested the SDRAM since my board doesnt have any of the others.
=> Updated the memory map for stm32f42xxx and stm32f43xxx devices.

src/stlink-common.c, src/stlink-common.h
This adds support for Cat.2 devices. Note that the old names (MEDIUM, MEDIUM+, HIGH) were all replaced with Cat.x in the datasheet.
=> Add STM32L1xx Cat.2 devices support

flashloaders/stm32f4lv.s, src/stlink-common.c
Per ST doc DM00035129.pdf "DocID022063 Rev 5", the STM32F415xx data sheet,
table 40 on page 110 of the PDF, 32-bit program operation is only possible
above 2.7 Volts.
In order to support programming on devices running at lower voltages, this
commit adds an 8-bit programming mode and the necessary tests to enable it
when the reported voltage is below 2.7 Volts.
=> STM32F4 8-bit support for 1.8v operation

gdbserver/gdb-server.c, src/stlink-common.c, src/stlink-common.h
This PR adds support for STM32F446x family.
Flashing and debugging has been tested with custom hardware with ST-Link v2 over SWD, and it generally works OK.
=> STM32F446 support

flashloaders/stm32l4.s, src/stlink-common.c, src/stlink-common.h
STM32L4 has a new chip ID and a re-organization of the flash controller's registers.
=> STM32L4 support

gdbserver/gdb-server.c, src/stlink-common.c, src/stlink-common.h
Device structure for STM32F746
Addded sram loader with DSM synchroisation barrier to ensure 32 bith writes to flash
GDB memory map for STM32F7
Tested with GDB in debug session, load from GDB to flash works.
Some debug messages concerning FP_CONTROL  but breakpoints work in GDB
=> Added STM32F7 Support

src/stlink-common.c
fix can not flash STM32_F3_SMALL, test on my STM32F302K8
=> fix can not flash STM32_F3_SMALL

src/stlink-common.c
The previous code for STM32F7 worked if binary size was less than 16kB, larger binaries would fail to load because of the difference in sector numbers for a given address since STM32F7 have flash sectors with double size compared to STM32F4.
=> Correct flash sector numbers and sizes for STM32F7

flash/main.c
st-flash used to fail in stlink_write_reg, when trying to start flash loader in RAM.
This patch makes st-flash work for me, target STM32F7 tested.
=> Make sure MCU is halted before running RAM based flashloaders.

src/stlink-common.h, src/stlink-usb.c
This change makes my board, STM32F7 Discovery actually reset
(final patch for today :) )
=> Make _stlink_usb_reset use hardreset

gdbserver/gdb-server.c
Fix a bug in gdb-server that failed to correctly compute the flash write size for a partial page at the end of a write block.
Fixes a segfault when loading an ELF file of just the right size onto an F4 chip made it try to copy past the end of the in-memory image.
=> Fix segfault in gdb-server

gdbserver/gdb-server.c
I was getting a segmentation fault error when programming a particularly large image into my Nucleo Board. I found this small passage of code that looks like is missing a variable update. After this change I've been able to program my board without getting the segmentation fault. My program runs fine, so the fix looks alright to me.
=> segmentation fault length fix

gdbserver/gdb-server.c
This pull request uses chip_id to integrate the breakpoint handling for M7 targets into the handling of M0/1/3/4 breakpoints. The number of hardware breakpoints is not fixed by a define but read from the FP_CTRL register.
Tested on the STM32F746 Discovery, but must be tested on other targets before commited into main.
=> Breakpoint handling for Cortex M7

src/stlink-common.c, src/stlink-common.h
STM32F469 is a STM32F429 MCU with Dual-QSPI NOR support and DSI screen
support.
Signed-off-by: Maxime Coquelin <mcoquelin.stm32@gmail.com>
=> Add support to STM32F469/STM32F479

flash/main.c, gdbserver/gdb-server.c, gui/stlink-gui.c, src/st-info.c, src/st-term.c, src/stlink-usb.c, src/stlink-usb.h, src/test_usb.c
This adds a parameter to the function stlink_open_usb and to the binary
st-flash to specify one of multiple connected stlinks.
As the identifier the iSerial of the stlink is used.
If no serial is given the function and binary behave as before.
=> Added parameter to specify one stlink v2 of many

README
Hello, checked this board with stink. It communicates without flaw with the board:
```
2015-12-15T14:47:03 INFO src/stlink-common.c: Loading device parameters....
2015-12-15T14:47:03 INFO src/stlink-common.c: Device connected is: L0x3 device, id 0x10086417
2015-12-15T14:47:03 INFO src/stlink-common.c: SRAM size: 0x2000 bytes (8 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 128 bytes
2015-12-15T14:47:03 INFO gdbserver/gdb-server.c: Chip ID is 00000417, Core ID is  0bc11477.
2015-12-15T14:47:03 INFO gdbserver/gdb-server.c: Target voltage is 3264 mV.
2015-12-15T14:47:03 INFO gdbserver/gdb-server.c: Listening at *:4242...
```
When I launch GDB and connect to the server, I get (updated with curent version of stink) :
```
2015-12-15T15:59:05 INFO gdbserver/gdb-server.c: Found 4 hw breakpoint …
```
=> Added STM32L053R8

gdbserver/gdb-remote.c
GDB doesn't need it and see the NUL as a junk character
(visible with 'set debug remote 1').
=> Do not send a NUL at end of packets to gdb.

gdbserver/gdb-server.c
So that 'extra' registers (msp, psp, ...) are visible to user.
=> stm32f7: also send features to gdb.

src/stlink-common.c
The STM32L4 specification specifies that VDD can be 1.71 - 3.6 V.
Signed-off-by: Greg Meiste <w30289@motorola.com>
=> Allow flashing of STM32L4 down to 1.71 V

src/stlink-usb.c
Previously when running the program, reading the chip version
would fail. Running the program a second time worked. This
sequence is repeated the next time st-flash/st-util is run.
Giving reset 10ms to complete before trying to read the chip
version resolves the issue.
Signed-off-by: Greg Meiste <w30289@motorola.com>
=> Fix issue where "unknown chip id!" is seen every other time

gdbserver/gdb-server.c
Previously, even with the reset enabled, st-util would not connect
to a target if it was running. This change will reset the chip
when opening the connection, which allows st-util to connect
successfully.
Signed-off-by: Greg Meiste <w30289@motorola.com>
=> st-util: Fix for connecting to running devices

src/stlink-common.c
After some time playing with the L4 chip, I realized that quite often the flash erase operation would just fail. Only thing that would make st-util work again was to perform mass erase using st provided st-link utility. Clearing SR before setting the PNB bits and also making sure the mass erase bits are off seem to have fixed it.
=> Stm32 l4 flash fix

gdbserver/gdb-server.c
Similar to #371.
I'm trying to backup the flash memory on an EMW3165 with an eBay ST-Link v2 using the following command:
```
$ gdb
GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin15.0.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos …
```
=> clamp gdb memory reads to 0x1800

src/stlink-common.c
I'm trying to backup the flash memory on an EMW3165 with an eBay ST-Link v2 using the following command:
```
st-flash read out.bin 0x8000000
```
I expect the output to be 0x80000 bytes in size but I get something quite shorter.  Appending the length to the command line also produces the same short output.  Looking at the code, I see that the number of FF's or 00's is counted on each iteration of the read, but the file is truncated after all of the reads are done.
I think the writes should be shortened inside the loop, but it looks like honouring `sl->q_len` is the way to go.
This patch removes the erased byte counter, bumps up the read size to min(0x1800, flash page size) similar to the verify flash data function.
=> remove empty byte truncation from stlink_fread

src/stlink-common.c, src/stlink-usb.c, src/stlink-usb.h
The st-link backend API is synchronous so just use the libusb synchronous API as well.  This lets us delete a bunch of code.
=> use libusb synchronous api

src/stlink-usb.c
`stlink_status` makes a call to `stlink_core_stat` which checks `q_len`.  The USB backend does not set this value.
Also remove some dead code in `stlink_open_usb`.
=> make usb backend status check work, remove some dead code

flash/main.c, gdbserver/gdb-server.c
.. because hitting CTRL-C and re-jigging the USB dongle is super annoying.
=> make st-flash clean up on sigint/term/segv, make gdb-server clean up on sigsegv.

gdbserver/gdb-server.c, src/stlink-common.c, src/stlink-common.h
Not a bug, just a slight improvement.
=> be quicker about determining erased byte pattern when flashing

CMakeLists.txt
It seemed the st-info tool was not added in the CMake build. This PR fixes it.
=> Add st-info to CMakeLists.txt

src/stlink-common.c
When writing binary images with a size larger than bank 1 size the first page (page 256 on a 512k dual bank Flash, see table 5, page 79 in  RM0351) on the second bank was not deleted (`rc/stlink-common.c` line 1200).
Before Modification
> EraseFlash - Page:0x80 Size:0x800 -> Flash page at addr: 0x08040000 erased
> EraseFlash - Page:0x101 Size:0x800 -> Flash page at addr: 0x08040800 erased
After modification:
> EraseFlash - Page:0x7f Size:0x800 -> Flash page at addr: 0x0803f800 erased
> EraseFlash - Page:0x100 Size:0x800 -> Flash page at addr: 0x08040000 erased
Further there are some improvements on the information output.
=> Proper writing of page 0 of second bank for stm32l476xe.

AUTHORS, CMakeLists.txt, Makefile.am, src/st-probe.c, src/stlink-common.h, src/stlink-usb.c, src/stlink-usb.h
Hi all,
I'm creating a continues integration system where a machine has multiple stlinks connected. There is currently no good auto-probe tool/library to find the current connected usb stlinks. With this autoprobe I generate openocd configurations to attach to all the programmers.
The following changes have been made:
* Added `stlink_probe_usb`
* Added `stlink_probe_usb_free`
* Extended `stlink_t with serial field`
* Added example CLI tool `st-probe`
Let me know what you think, there is a little code duplication with this addition but the current `stlink_open_usb` is way to big for me to refactor. I tried to refactor the `stlink_open_usb` function but failed and broke the whole thing.
Here is some example output:
```
jjacobs@workbench ~/repos/github/stlink/build $ ./st-probe
Found 2 …
```
=> st-probe: Initial working stlink_probe_* API and CLI tool

src/st-probe.c, src/stlink-common.c, src/stlink-usb.c
With addition of st-probe, it was not previously tested when programmers are already busy. The `stlink_open_usb` then passes a null pointer into the list of programmers. Then on-close it segfaults on the NULL pointer. With this PR it is hardended against NULL pointers.
=> st-probe: Fix segfault when programmer is already busy

CMakeLists.txt
When integrating the stlink as a library into a C++ application the CMakeLists where missing the -fPIC compiler flag and the st-info.c was double linked into the st-info tool (libstlink.a and st-info).
=> Add -fPIC compiler flag, remove st-info from libstlink.a

.travis.sh, .travis.yml, README
This catches bugs earlier for both CMake and Autotools build system as seen in #403 by travis.
It is a bit odd to take care for two build systems, but people can use now what they prefer.
=> Travis add autotools build

include/stlink.h, src/common.c
support for STM32L0 category 5 devices
tested on L073RZ
flash and sram sizes specified are the biggest possible ones
=> Add support for L0x Category 5 devices

flashloaders/stm32l0x.s, flashloaders/stm32lx.s, src/common.c
In response to issue #390, I have reverted the two commits (907383da8ef95fedc630cdf7cf102d44ae229200 and e43a737c3c9ffe56045181b306509c942fd9998a) that were causing issues for people with STM32L0's and STM32L1's.
=> Fix for broken STML0 and STML1

include/stlink.h, src/common.c
I tried it with: [NUCLEO-L031K6](http://www.st.com/web/catalog/tools/FM116/CL1620/SC959/SS1532/LN1847/PF262547)
I'm not sure about the sram_size, but based on [this](http://www.st.com/web/catalog/mmc/FM141/SC1544/SS1833/LN1862) and [RM0377](http://www.st.com/st-web-ui/static/active/en/resource/technical/document/reference_manual/DM00108282.pdf) every category 2 device has 8 kB SRAM (now).
=> Add L0 Category 2 device (chip id: 0x425)

src/chipid.c, src/common.c
Just fix the 2 warnings:
warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
=> Fix const warning on struct stlink_chipid_params

.travis.sh, .travis.yml
Enable gcc 5 and clang 3.8 compilers for Travis continuous integration
=> travis: Add gcc-5 and clang-3.8 to matrix for linux cmake builds

src/gdbserver/gdb-server.c
=> Don't read the target voltage on startup, because it crashes STM32F100.

src/usb.c
=> Add a useful error message instead of "[!] send_recv"

include/stlink.h, include/stlink/chipid.h, src/chipid.c, src/flash_loader.c
=> Support stm32f7x7x

src/common.c, src/flash_loader.c
Since STLINK V1 cannot read voltage, and attempting to do so breaks the
USB communications, this patch will revert the behaviour to just blindly
doing 32-bit writes on these programmers.
=> Fix a regression introduced in 71535104.

src/common.c
I run into flashing error with stm32f030. With some
debugging I find out that the mass erase bit was dropped
when flash programming bit already set on FLASH_CR.
This cause erase and write error with my stm32f030
board.
Mass erase never need the programming bit. Turn off the
programming bit make stlink flash stm32f030 successfully.
=> Fix an erase error in stm32f030 device.

src/common.c, src/gdbserver/gdb-server.c
The STM32F76XXX having a different Chip ID than the STM32F74x, we need to check for the Core ID for STM32F7-specific handling.
=> Fix gdb and flash support for the STM32F769I-Disco board.

src/usb.c
When a microcontroller is in deep sleep (stop) mode, its debug interface is turned off. Programming would therefore fail because st-flash was unable to identify the CPU. This change adds a JTAG reset prior to requesting CPU information. This change has been successfully tested with a Nucleo STM32L031 board.
=> Do a JTAG reset prior to reading CPU information

CMakeLists.txt, src/gdbserver/gdb-server.c, src/gdbserver/semihosting.c, src/gdbserver/semihosting.h
I call this patch a prototype because it supports only two of the ARM semhosting operations (WRITEC and WRITE0).
=> Prototype of ARM semihosting support

src/gdbserver/gdb-server.c, src/gdbserver/semihosting.c
This patch adds the following operations:
- SYS_OPEN
- SYS_CLOSE
- SYS_WRITE
- SYS_READ
- SYS_ERRNO
- SYS_REMOVE
- SYS_SEEK
The use of utility functions mem_read() and mem_write() add an
unnecessary memcpy() call. All buffer transfer could be done directly in
the sl->q_buf data instead of using a temporary transfer buffer.
However, given the relative slowness of target memory transfer, I don't
think that this has a big impact on performances
=> Improve ARM semi-hosting support

src/chipid.c, src/gdbserver/gdb-server.c
Also:
- fixed a typo in an if statement condition in make_memory_map
- cleaned up usage of '4096' in favor of const size_t sz = 4096.
=> Fix memory map for STM32F7xxx

CMakeLists.txt, include/stlink.h, include/stlink/tools/flash.h, src/common.c, src/tools/flash.c, src/tools/flash_opts.c, tests/CMakeLists.txt, tests/flash.c
Hi
here is my implementation of Intel-HEX format for st-flash (both reading and writing). The format can be selected with new command line option '--format=ihex' (one may not specify <addr> for write with the format, the address will be taken from input file).
Additionally I've re-designed the command line parsing, because it was too complicated with the new option. And added some unit-tests for parsing itself to guaranty all old options still work.
Unfortunately it's not so easy to split this pull request to single features, but I could try if you prefer.
WMBR,
dev26th
=> Support of Intel-HEX format for st-flash

src/gdbserver/gdb-server.c
Trying to load a elf image on a stm32f401xe can result in a problem
of flash write if a section does not start on a flash sector because
the memory map given to gdb was wrong.
=> Add memory map for stm32f401xe

src/usb.c
This works around issue #480.  I'm not sure if it is the correct way to fix it.  It is tested and works here on a stlink-v1 board.
=> Do not issue JTAG reset on stlink-v1

include/stlink/chipid.h, src/chipid.c, src/common.c, src/flash_loader.c
=> stm32l432 support

CMakeLists.txt, debian/rules, doc/compiling.md
I had two problems while packing stlink for Arch Linux (this package: https://aur.archlinux.org/packages/stlink-git/):
1. The file `etc/modprobe.d/stlink_v1.conf` is installed to `/etc/stlink_v1.conf`. The subdirectory `modprobe.d` is not created. I'm quite sure that this is true for other distributions too. The first patch of the patch set should solve that.
2. The udev-rules are installed to the absolute location `/lib/udev/rules.d`. In Arch Linux, `/lib` is only a link to `/usr/lib`. To create a package, I have to be able to install the files to `/usr/lib`. To fix this, I just applied the `CMAKE_INSTALL_PREFIX` to this path too. I'm not sure if this is OK for other distributions too. Would it be better to use some other variable like `CMAKE_LIBRARY_PREFIX` instead?
=> Fix install locations for modprobe config and udev rules

doc/man/st-flash.md, include/stlink/tools/flash.h, src/tools/flash.c, src/tools/flash_opts.c
st-flash does now have a 'reset' command
makes it easy to reset the Target
=> flash: added easy way to reset the target

include/stlink.h, include/stlink/backend.h, src/common.c, src/usb.c
- Fixed bug where stlink_jtag_reset in stlink_open_usb() was never being called because the STLINK version was being checked before it had been initialized
- Added support for stlink_set_swdclk() to adjust the SWD clock speed.  For example, to set at 4Mhz, 1.8Mhz, 900Khz, etc similar to in the official ST-LINK utility.  NOTE: The default when STLINK is powered appears to be 1.8Mhz (looked at scope traces) but it retains whatever was set before.
=> Set SWDCLK and fix jtag_reset bug

src/common.c
otherwise all subsequent erases before turning off the power will be mass erases
=> reset MER bit after mass erase

include/stlink/chipid.h, src/chipid.c, src/flash_loader.c
General support for STM32F412 devices.
Added chipid, device params and fixed condition in flash_loader.c
Checked on 32F412GDISCOVERY kit board.
=> add support for STM32F412

src/sg.c
following warning:
warning: missing initializer for field ‘set_swdclk’ of ‘stlink_backend_t
{aka struct _stlink_backend}’ [-Wmissing-field-initializers]
silence the warning and expand comment
=> after 4c69cae257e317e9297f5a89eed940313b9c25c2 a compile produces the

src/gdbserver/gdb-server.c, src/tools/flash_opts.c
modified serialnumbersupport in st-flash:
in flash_opts take care of the length of the given serialnumber (was fix 12 chars)
added serialnumber support in st-util:
implemented like in st-flash.
=> serialnumber support  st-util and st-flash

include/stlink/tools/flash.h, src/common.c, src/gdbserver/semihosting.c, src/tools/flash.c, src/tools/gui/CMakeLists.txt, tests/flash.c
Here some fixes for Linux Manjaro (Arch based)
Thanks for your project which I use for flashing OpenTX
https://github.com/opentx/
Semihosting still doesn't work, I will try to debug it if it works correctly with openOcd
=> Compilation fixes (errors / warnings)

src/tools/gui/CMakeLists.txt
Currently compilation of `release` would break when the path to `stlink` included spaces. There seemed to be no proper way to fix this by escaping within `COMPILE_FLAGS`, but since CMake 3.0 there is a `COMPILE_DEFINITIONS` property that handles escaping itself.
=> Fix compilation when path includes spaces

flashloaders/stm32f7.s, flashloaders/stm32f7lv.s, src/flash_loader.c
Added stm32f7.s and stm32f7lv.s (the sooner was already supported but probably the definition of loader_code_stm32f7  in flash_loader.c was just winged from the F4 version by manually adding the opcode for the "dsb").
Instead of copy & paste the voltage detection code, I refactored it into a function. If that is not cool, let me know and I can revert that part.
Also, I haven't got a chance to test it out on an M4 yet. Will do over the weekend.
=> Fixing low-voltage flashing on STM32F7 parts.

src/gdbserver/gdb-server.c, src/tools/info.c
`%zx` gets printed as `zx`. Just using `%x` suffices in the cases in this PR.
This fixes stlink for us.
=> Fix stlink on mingw64

src/usb.c
=> Fix possible memory leak

src/gdbserver/gdb-server.c, src/tools/info.c
Reverts texane/stlink#569
This breaks the build on other systems which is more correct than fixing the mingw64 build:
Issue introduced:
```
[ 37%] Building C object CMakeFiles/st-info.dir/src/tools/info.c.o
/var/lib/jenkins/jobs/GithubCI/jobs/stlink/workspace/src/tools/info.c: In function ‘print_data’:
/var/lib/jenkins/jobs/GithubCI/jobs/stlink/workspace/src/tools/info.c:117:9: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t’ [-Wformat=]
printf("0x%x\n", sl->flash_size);
^
/var/lib/jenkins/jobs/GithubCI/jobs/stlink/workspace/src/tools/info.c:119:9: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t’ [-Wformat=]
printf("0x%x\n", sl->sram_size);
^ …
```
=> Revert "Fix stlink on mingw64"

doc/man/st-flash.1, doc/man/st-flash.md, include/stlink/tools/flash.h, src/tools/flash.c, src/tools/flash_opts.c
By default, st-flash works the same as before (there is no more chipid override in this pull request).
Now _optionally_, you can specify **--flash=128k** for example, to override the stm32f103c8t6 to assume 128k of flash instead of the default of 64k. This option accepts decimal (128k), octal 0200k, or hex 0x80k. Obviously leaving the multiplier out is equally valid, for example: --flash=0x20000
The size may be followed by an _optional_ "**k**" or "**m**" to multiply the given value by 1024 or 1 Meg respectively.
Tests on the stm32f103c8t6 confirm that overriding the flash size is all that is required. I was still able to flash and read 128k without changing the chipid. I don't know if this will be true of all other devices but I suspect that they will.
=> Added --flash=n[k][m] command line option to override device model

CMakeLists.txt, usr/lib/pkgconfig/CMakeLists.txt
There is no way to reliably configure installation path for shared
objects.  It looks like this should be configurable by setting
CMAKE_LIBRARY_PATH but this approach doesn't work as intended.
Moreover, according to cmake docs, purpose of this variable is slightly
different.
With this patch it should be possible to configure where all libs should
go by setting STLINK_LIBRARY_PATH to either /usr/lib or /usr/lib64
(/usr/lib64 is new default value assuming that most users run 64bit
systems).
=> Fix installation path for shared objects

CMakeLists.txt
It seems that stlink cannot use CMake's standard mechanism to find GTK3.
Cmake's GTK3 detection supports only Unix at the moment.
Therefore, stlink uses pkg-config to find GTK3. The downside of this is
that Cmake's cross-compiler settings are not taken into account. Even if
we're cross-compiling, CMake will find a local installation of GTK3 and
compilation of the GUI fails.
As a simple fix, we skip the GTK3 detection if we're cross-compiling.
(In the long run, we should use a more advanced mechanism to find GTK3.)
=> skip GTK detection if we're cross-compiling

include/stlink.h, src/chipid.c, src/common.c, src/flash_loader.c
Some of the chips in the STM32F10x series has two separate flash banks. The first is always at most 512kB and the size of the second can be 0, 256 or 512 kB. For example, the STM32F103RF has 512 + 256 kB of flash memory. To be able to flash the second you need to use another set of registers instead of the usual SR/CR/AR registers. I made a patch for this that works for me(tm). Let me know if I should change anything; would be nice to get this included in upstream!
=> Added support for flashing second bank on STM32F10x_XL

src/common.c
Fixes issue #594.
Pull request #592 (0498621) accidentally deleted the call to `set_flash_cr_pg`.
=> fix flashing to 'f0 device' targets

src/common.c
When flashing STM32F1 models, the counting is off by one (e.g. when flashing 8188 bytes it counts from "0/7 pages written" to "7/7 pages written". This small patch fixes this (1/8 --> 8/8)
=> Fix wrong counting when flashing

.gitignore, debian/.gitignore, doc/tested-boards.md, include/stlink/chipid.h, src/chipid.c, src/flash_loader.c
Unfortunately, I crammed 2 commits into this PR. The first deals with temporary files generated by `dpkg-buildpackage` on Debian stretch. The second should fix #603.
=> Fix gitignore and add support for STM32L452

include/stlink/chipid.h, src/chipid.c, src/flash_loader.c
Hi,
I quickly added the support of my STM32L496G (discover) in stlink.
I can read and write data to the micro-controller memory. I think all is good.
Before write to the flash, I do a mass erase otherwise it fails with this message:
> 2017-07-14T15:48:32 ERROR src/common.c: Verification of flash failed at offset: 6144
Regards,
Anthony V.
=> Add support of STM32L496xx/4A6xx devices

src/common.c, src/gdbserver/gdb-server.c
There were missing chipid checks of STM32L496xx and STM32L46x devices.
=> Fix verification of flash error for STM32L496x device (#617)

README.md
was just single quotes instead of back ticks
This is pretty self explanatory.  It just irked me when I opened your readme, sorry if this PR doesn't follow a template I just did this real quick
=> minor formatting fix in FAQ section of readme

README.md
I am just added stlink package to Fedora and EPEL repositories. It available now for Fedora Rawhide, after 7-8 days other Fedora and after 14-15 days for EPEL.
If someone need stlink for RedHat/CentOS 6 it may be done later and without GUI because GTK 3 not available.
=> Added information about Fedora and RedHat/CentOS packages.

CMakeLists.txt, doc/compiling.md
=> Added LIB_INSTALL_DIR to correct libs install on 64-bit systems

src/common.c
This fix is due to a problem to flash STM32F410 with large .bin (for example nuttx.bin). The result is :
st-flash 1.4.0-8-g1700e6a
2017-09-16T17:15:20 INFO src/common.c: Loading device parameters....
2017-09-16T17:15:20 INFO src/common.c: Device connected is: F410 device, id 0x10006458
2017-09-16T17:15:20 INFO src/common.c: SRAM size: 0x8000 bytes (32 KiB), Flash: 0x20000 bytes (128 KiB) in pages of 16384 bytes
2017-09-16T17:15:20 INFO src/common.c: Attempting to write 57728 (0xe180) bytes to stm32 address: 134217728 (0x8000000)
Flash page at addr: 0x0800c000 erasedEraseFlash - Sector:0x3 Size:0x4000 
2017-09-16T17:15:21 INFO src/common.c: Finished erasing 4 pages of 16384 (0x4000) bytes
2017-09-16T17:15:21 INFO src/common.c: Starting Flash write for F2/F4/L4
2017-09-16T17:15:21 INFO …
=> fix write for microcontroler with RAM size less or equal to 32K

src/gdbserver/gdb-server.c
STM32l496xx boards had incorrect configuration of the memory map, making memory inaccessible inside GDB.
To see the fix is right, take a look at http://www.st.com/content/ccc/resource/technical/document/reference_manual/02/35/09/0c/4f/f7/40/03/DM00083560.pdf/files/DM00083560.pdf/jcr:content/translations/en.DM00083560.pdf section **2.6.2 Boot configuration for STM32L496xx/4A6xx devices** table 7.
=> Fix memory map for stm32l496xx boards.

include/stlink/chipid.h, src/chipid.c, src/common.c
The reason for my proposal of adding a dummy for the unknown chip is that I wanted to obtain the serial of the ST-link by a call to `st-info --probe`. This returns nothing (not even a warning) when an unknown chip is attached (in my case an NXP lpc17xx). With the changes here, I could easily obtain the serial, which I needed in OpenOCD, as multiple programmers are attached. (BTW: Although not supported, I am able to flash the chip, mentioned above)
=> add unknown chip dummy

debian/triggers
After installing the deb package, st-util fails to start:
> $ st-util
> st-util: error while loading shared libraries: libstlink-shared.so.1: cannot open shared object file: No such file or directory
The reason is, no one ran `ldconfig` upon installing the library.
The solution, as per latest Debian recommendations [1], is to add an ldconfig trigger in `debian/triggers`, which is what this commit does.
[1] https://www.debian.org/doc/debian-policy/#ldconfig
=> debian/triggers: add (to run ldconfig)

src/tools/gui/stlink-gui.c, src/tools/gui/stlink-gui.h, src/tools/gui/stlink-gui.ui
Hello
I added a button to export the flash memory to a file.
Is it possible to merge it in the master ?
=> Adding button to export stm32 flash memory to a file

include/stlink/chipid.h, src/chipid.c, src/flash_loader.c
https://github.com/texane/stlink/issues/694
=> Add support for STM32L4R9

include/stlink/chipid.h, src/chipid.c, src/flash_loader.c
STM32L4R5ZI uses the same chip id, the reference manual (DM00310109.pdf) is the same for all L4Rxxxx devices.
=> rename STLINK_CHIPID_STM32_L4R9 to STLINK_CHIPID_STM32_L4RX

src/gdbserver/gdb-server.c
I was having trouble loading .elf files for the Multitech mDot using the default memory map. 
Thanks!
Dacoda Strack
=> send memory map for STM32F411RE

src/common.c, src/flash_loader.c
The F722RE uses the same flash memory map as 512kB flash f4 series. Without these changes the flash would be erased in pages of 2048bytes, rather than the full 16/64/128kb blocks on the hardware.
All the F72x and F73x devices have this same memory layout, so should be fixed by this commit.
=> Fixed flash memory map for F72XXX chip_id

include/stlink/reg.h, src/sg.c, src/usb.c
In addition to asserting the NRST line, also request system reset through the
Application Interrupt and Reset Control Register (AIRCR).
This patch has been tested against an STM32L071 using the SWD without connecting the NRST pin.
=> Reset through AIRCR (#540)

src/tools/gui/stlink-gui.c
#713 The GUI interpreted all files as binaries. Try to load '*.hex' as Intel-HEX
=> implement IHEX for the GUI

src/gdbserver/semihosting.c
Use local variable for read_result instead of *ret, and fix calculation of *ret for EOF case.
=> For Issue 726, Semihost SYS_READ returns incorrect value on EOF

src/gdbserver/semihosting.c
I agree with Fabien-Chouteau's review items. Thanks for catching my sloppy errors.
Here is a PR with those things fixed.
=> Fixes to SYS_READ changes in PR #727 per review.

doc/tutorial.md, src/gdbserver/semihosting.c
As slyshykO notes in #729, read_result is a signed type so the -1 constant should not be cast to unsigned.
I belive compilers will be happy with this without any cast.
=> Fix to cast in changes for SYS_READ.

src/gdbserver/semihosting.c
Here is the first fix to mem_write() again.  This is simply to have it return when len == 0 and that solves my issues with reading at the end of a file when the remaining data is not an even multiple of 4 bytes.
I have also recognized that this function will overwrite target data that is shouldn't if it is ever called with a non-zero length and either the address or length is not a multiple of 4.  I don't know if that situation will ever occur, it does not happen in my limited uses (so far :-) ).  I have added some comments with possible ways to address that issue.
=> Mem write odd

src/sg.c
LIBUSB_API_VERSION is not defined on FreeBSD, so it fail to compile.
=> FreeBSD define LIBUSB_API_VERSION instead of LIBUSBX_API_VERSION.

include/stlink/chipid.h, src/common.c
RM0394 covers the STM32L41xx, 42xx, 43xx, 44xx, 45xx, and 46xx. These
devices are all employ single banked flash and have chip id's
of 0x464 for the 41xx/42xx, 0x435 for 43xx/44xx, and 0x462 for 45xx/46xx
It's also worth noting that bit 21 of the FLASH_OPTR register is marked
as resevred for these chips, and isn't an indicator of dual banked
flash.
RM0392 covers the STM32L4x1, cpu_id 0x415 and can be dual banked.
RM0351 covers the STM32L4x5/4x6, cpu_ids 0x415 & 0x461 and can be dual
banked
RM0432 covers the STM32L4Rx/4Sx, cpu_id 0x470 and can be dual banked.
This PR modifies the calculate_L4_page functio to only factor bank
calculations for the devices above which can support dual banked flash.
I also checked the STM32L4 HAL code and it uses the following preprocessor #if statment
```
#if …
```
=> Only do bank calculation on STM32L4 devices with dual banked flash

src/common.c
O_BINARY option while opening file for binary write is needed for proper function in Windows. The option should be harmless for linux.
See issue #752.
=> Add O_BINARY option to open file.

include/stlink.h, src/flash_loader.c
Fixes #756 
I'm pretty sure the name `CS32_CORE_ID` is not appropriate so tell me what I should use.
I have tested and it works, I can upload the STM32duino bootloader on the CS32F103C8T6 board just fine.
=> Add support for CS32 micro-controller

src/chipid.c
The 'F334' chip ID looks like it also covers a few smaller F3 devices - see RM0316 section 33.6.1, "MCU Device ID Code":
https://www.st.com/resource/en/reference_manual/dm00043574.pdf
I don't know what to write for the description, though; 'F3xx medium density device' probably isn't that great.
=> Update STM32F3xx chip ID that covers a few different devices.

src/tools/gui/CMakeLists.txt
Fixes #770.
Either of the following work now:
* `mkdir build; pushd build; cmake ..; make -j32 all; ./src/tools/gui/stlink-gui-local; popd`
* `cmake .; make -j32 all; ./src/tools/gui/stlink-gui-local`
This issue most likely has been caused by 4209e4b92416, as `CMAKE_CURRENT_SOURCE_DIR` is interpreted as currently processed source directory and that changed by moving cmake source to different directory.
=> gui: Fix relative path to the UI files needed by stlink-gui-local

doc/compiling.md
the command 'debuild' is (and always was) part of the devscripts package
=> doc/compiling.md: fix package name "devscripts"

src/common.c
The st-flash write utility wasn't clearing the PG bit after it finished writing to Flash.
Luckily you've already implemented the function for clearing the PG bit, so I just added the call right before locking Flash CR again.
The reason this is important is that if I just flashed a firmware, then any subsequent operation will fail, until I clear the PG bit, so I'll have to add code just for that one case. Or a simple power cycle the STM32 clears it.
Anyway it's just a convenience for the flasher utility to clean up after itself :)
=> Added call to clear PG bit after Writing to Flash

README.md, include/stlink.h, include/stm32.h, src/common.c, src/tools/flash.c
=> Added support to write option bytes for the STM32G0

include/stlink.h, include/stlink/chipid.h, src/chipid.c, src/common.c
This adds support for STM32WB55 chips - I've only tried a simple 'blink' program on the 'Nucleo-68' board, but it seems to work.
The logic and register offsets look about the same as the STM32G0 series, though - I might check if it would be easy to merge that logic, or maybe adapt it to the other chips' abstractions like `set_flash_cr_pg(...)`. Would that be better?
=> Add simple read/write support for STM32WB55 chips.

etc/udev/rules.d/49-stlinkv3.rules
Added STLink V3 VID:PID to the udev rules. 
Source of the VID:PID list is the openOCD (Antonio who wrote the openOCD patch has some docs from ST, so the list should be valid):
http://openocd.zylin.com/#/c/4717/3/contrib/60-openocd.rules
Adding support for the V3 just the matter of a few adjustments (different endpoints, etc.), what I am planning to implement in texane-stlink soon.
=> Add STLink V3SET VID:PIDs to the udev rules

etc/udev/rules.d/49-stlinkv2-1.rules, include/stlink/usb.h, src/usb.c
Why? 
Flashing "STM32+Audio" is only way for have St-link v2-1 with UART on stm32f103c8. 
Other firmwares can't be flashed with ST Utils ("firmware is too big"). 
```
$ lsusb
...
Bus 002 Device 098: ID 0483:374a STMicroelectronics
...
```
Brefore patch:
```
$ sudo st-info --probe
Found 0 stlink programmers
```
After patch:
```
$ sudo st-info --probe
Found 1 stlink programmers
serial: ...deleted...
openocd: "...deleted..."
flash: 65536 (pagesize: 1024)
sram: 20480
chipid: 0x0410
descr: F1 Medium-density device
```
=> Support for "STM32+Audio" v2-1 firmware

src/common.c, src/gdbserver/gdb-remote.c, src/gdbserver/gdb-server.c, src/gdbserver/semihosting.c, src/mingw/mingw.c, src/mingw/mingw.h, src/mmap.c, src/sg.c, src/usb.c
=> fixed few potential memory/resource leaks

include/stlink.h, include/stlink/tools/flash.h, include/stlink/usb.h, src/usb.c
On Nucleo boards the serial gets truncated. This allows for longer serials.
=> Allow for 64 Bytes serials (with new Nucleo-L476RG)

src/flash_loader.c
CS32F103C8T6 is clone of STM32F103C8T6 but with incorrect core_id number. ( #757 )
All original STM32F1xx has core id STM32VL_CORE_ID, but CS32F103 has different core id 0x2BA01477 (as original STM32F3xx, STM32F4xx and STM32L1xx).
This commit should not affect other devices because all original STM32F1xx (include STLINK_CHIPID_STM32_F1_MEDIUM) has core id STM32VL_CORE_ID.
=> Add support for CS32F103C8T6

src/common.c
It seems that `PNB` (page number) bit field wasn't properly written to, as previously set bits wasn't cleared by subsequent logical-or `|=` writes. That is probably the cause of #810 and I was able to reproduce a similar error and this change fixes it.
@section14, please test that this change fixes the error you got in #810.
=> WB55: fix flash verification error

src/common.c
stlink seems to be unable to read flash size on stm32discovery F1 VL (stlink-v1):
st-flash 1.5.1-32-g4909dd8
2019-09-02T17:49:05 INFO common.c: Loading device parameters....
2019-09-02T17:49:05 INFO common.c: Device connected is: F1 Medium/Low-density Value Line device, id 0x10016420
2019-09-02T17:49:05 INFO common.c: SRAM size: 0x1000 bytes (4 KiB), Flash: 0 bytes (0 KiB) in pages of 1024 bytes
Since the flash size is equal to zero stm32F1 cannot be flashed with :
Unknown memory region
This patch add a work around like for L1 to fix manually size if value read equal 0.
=> Fix flash size of stm32discovery vl

README.md, include/stm32.h, src/common.c, src/tools/flash.c
We use it in production to do a mass erase for removing the LEVEL_1 access protection flag
=> added support for writing option bytes on STM32L0

include/stlink.h, include/stlink/tools/flash.h, include/stm32.h, src/common.c, src/tools/flash.c, src/tools/flash_opts.c
Option Bytes were not accessible for STM32F2 devices, so I added read/write command for Option Bytes on STM32F2 devices.
st-flash --reset --area=option read > option_byte 
st-flash --reset --area=option write 0x0FFFAAE0
=> Added Read/Write command for Option-Bytes on STM32F2 series 

src/tools/flash.c
When flash size and addr are valid, stlink_fread command was not executed. 
notified by https://github.com/texane/stlink/pull/836#discussion_r332710245
=> bug fix: Flash read operation was not executed

src/common.c
=> Fixing verification fail for chip ID L4RX

include/stlink.h, src/common.c, src/tools/flash.c
Only tested on STM32F446 devices currently. Change STLINK_CHIPID_STM32_F446 references if you want to use this on another F4-based chip.
=> Allow reading/writing option bytes to STM32F446 devices

doc/developer.txt, include/stlink.h, src/common.c
Thanks a lot for "stlink". I started to make myself a little bit more familiar with the software structure. 
I added a document (developer.txt) and some comments here and there.
Of course still a lot more could be done...
Maybe it is useful to others (especially because you look for a new maintainer).
There no code changes in this pull request, just comments...
=> added several comments on the stlink software structure

include/stm32.h, src/common.c, src/flash_loader.c
after the flash loader ran the PG bit is still set in the CR register.
in order to program the next page that page needs to be erased first and to get that working the PG bit has to be cleared so the flash controller knows what to do.
this fixes #579
=> clear the PG bit before setting the PER bit

src/chipid.c, src/flash_loader.c
It seems my code also has the F72 fix. Do you really need that in a separate pull request?
Looking at that: Shouldn't it be "F72x / F73x device"? Wouldn't that be clearer? All devices have a 3-digit type number. I noticed that I often use the F072, but thats a different beast than the F72x and F730....
=> Fixed wait-loop for flash_loader_run() & F72/F73 device description

src/usb.c
Separate pull request for separate issue. On error in probe, the 1.6 version did not error out. This seems due to wanting to save a couple of lines that didn't work out. I added the two necessary lines.
=> Error return in failed probe (Fixes #887)

src/chipid.c, src/common.c, src/gdbserver/gdb-server.c, src/usb.c
As requested. The startup of st-util is now: 
```
assurancetourix:~> ~/stm32/stlink.git2/build/Release/src/gdbserver/st-util -m
st-util 1.6.0-33-gb8813fa-dirty
2020-03-21T16:07:15 INFO common.c: F0xx small: 4 KiB SRAM, 16 KiB flash in 1 KiB pages.
2020-03-21T16:07:15 INFO gdb-server.c: Listening at *:4242...
```
The user may want the "listening at" message and the "what's connected" message has been reduced from two lines to just one. It now contains just the info that normal users may want to know.: stuff that helps determine if say the right target is connected. 
I removed all the "device" parts of the strings in the description of the chipID table. 
Some of the "description" entries in the table had a check for say a CHIPID_F412 and then proceded to call the device an F4xx. Lets just …
=> Silence unnecessary messages (Fixes #240)

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, src/common.c, src/usb.c
Make stlink build on 32 bit systems.
Build passed on ubuntu 16.04 i386 and macOS Mojave 10.14.6 AMD64.
`make test` failed for flash, which seems to be the same as current master.
Related issue:
[https://github.com/texane/stlink/issues/629](https://github.com/texane/stlink/issues/629)
=> Fix int length issues

src/chipid.c
- Add id and infos for stm32g47/48 chips.
- Update comments regarding g43/g44
I followed current g43x scheme of considering sram1/sram2/ccm sram as contiguous, but documented it. 
Note that I've only worked with the first of the two banks. stm32g474 can also be configured as a single 512kb bank, with 4k pages via option bytes. but i think there's no logic to handle that properly ?
=> stm32g4 chips update

include/stlink.h, include/stlink/chipid.h, src/chipid.c, src/common.c
Hi,
here are a few patches to improve g4/g0 support
- introduce a helper to handle devices with dual bank flash
- handle cat3 g4 devices with configurable dual bank flash
- enable mass erase for g4 and g0 devices. 
- add a flash programming check at the end of mass erase.
has_dual bank flag could probably avoid multiple device type check around the code with a bit of work. 
flash programming check could probably be added in page erase and flash write and extended to other devices, to debug some silent issues.
=> stm32gx improvements

src/gdbserver/gdb-server.c
* Fix by adding error handler in gdb-server
* Enhance logs for functions with return values
Fixes:
https://github.com/texane/stlink/issues/780#event-3213582141
=> Fix dead loop after an unexpected unplug

include/stlink/usb.h, src/usb.c
Hi,
here's a small patchset to fixup st-info probe mecanism and lower layers.
- handle stlink v1
- fetch serial info for all stlinks
- return proper number of functionnal and connectable stlinks
- fix probe fail when one stlink v1 and more recent one are connected
- add macros for usb pid filtering.
This has been tested with a couple of devices connected (v1, v2, v2.1 and v3). Note that it seems that all v1 have the same serial, so, i guess that selecting them will be complicated - there's apparently some kind of hidden env variable filter mecanism based on usb addr in addition to the --serial parameter, but i've not tested it.
> Found 3 stlink programmers
>  serial:     493f6c06483f53491743073f
>  hla-serial: "\x49\x3f\x6c\x06\x48\x3f\x53\x49\x17\x43\x07\x3f"
>  flash:      32768 …
=> Fixed st-info --probe mechanism

src/common.c, src/gdbserver/gdb-server.c
Fixes https://github.com/stlink-org/stlink/issues/919
=> Fixed broken build on 32-bit systems

src/common.c
Trying to improve for https://github.com/stlink-org/stlink/issues/650
=> Enhance error log with file path for map_file()

src/tools/flash.c, src/tools/flash_opts.c
Somewhat fix the help message that showed some parameters as mandatory,
when in reality they depend on the operation type and file format.
Try to show explicit error messages for the most common mistakes.
=> st-flash: minor usage fix, and make cmdline parsing more user friendly

src/tools/flash.c, src/tools/flash_opts.c
flash.c: stlink_open_usb is actually able to open v1 and v2 (and v3 .…….)** devices.
no need to check that _not used_ o.devname ..
no need to specify devname in commandline
get rid of the devname cmdline stuff, and update comments
should probably help with #378 ..
=> flash.c: stlink_open_usb is actually able to open v1 and v2 (and v3)

src/common.c, tests/usb.c
Fixes https://github.com/stlink-org/stlink/issues/937
=> Fix uninitialized cpuid

src/gdbserver/gdb-server.c, src/tools/flash.c, src/usb.c
stlink_open_usb now returns without failure when no target is detected, or when target is not fully handled. Fix behaviour of tools in that case.
nb: st-util handling should maybe be discussed. currently it allows to start with no supported flash, which is what i would expected from a debugging tool, but flashing wont work obvs.
refs #432
=> handle probed stlink with unconnected target properly

doc/man/st-flash.md, doc/man/st-info.md, doc/man/st-util.md, doc/tutorial.md, src/gdbserver/gdb-server.c
=> st-util: removed now useless v1/v2 STLink version stuff

include/stlink.h, src/chipid.c, src/common.c
hi,
Some more work on flash handling, mostly around implementing and reflactoring register access and flash locking helpers. option write/read device specific has been refactored based on the main flash familly, and f0 support primitives have been added.
a second pr will follow later to support then.
=> [refactoring] Cleanup for option bytes and flash settings

doc/tutorial.md, include/stlink.h, include/stlink/tools/flash.h, src/st-util/gdb-server.c, src/stlink-gui/gui.c, src/tools/flash.c, src/tools/flash_opts.c, src/tools/info.c, src/usb.c, src/usb.h, tests/flash.c, tests/usb.c
Fix https://github.com/stlink-org/stlink/issues/893
* Add --freq argument for st-flash
=> [feature] Adjust the JTAG/SWD frequency via cmdline option

flashloaders/stm32f0.s, src/flash_loader.c, src/usb.c
Move the two nop instructions previously appended to the front of the binary to the assembly file.
Fixes https://github.com/stlink-org/stlink/issues/958
=> Fixes for STM32F0 flashloader (Closes #958)

.vscode/settings.json, include/stlink/tools/flash.h, src/tools/flash_opts.c, src/tools/info.c, src/usb.c, src/usb.h, tests/usb.c
I've added a small change to stlink_open_usb to support connect under reset.  In addition, I added an option to tests/usb.c  (--reset or --no-reset) to use this mode.
=> [feature] Added connect under reset to stlink_open_usb( )

doc/man/CMakeLists.txt
On Unix-like operating systems man pages are commonly installed to
`/usr/share/man` not `/usr/share/stlink/man`.
---
Also: I noticed the pkgconfig file is no longer installed by default, how do I fix that?
=> doc/man: Fix installation directory

src/stlink-gui/CMakeLists.txt
This change fixes installation path for desktop-file and icons.
They should be installed directly to
```
/usr/share/applications/
/usr/share/icons/hicolor/scalable/apps/
```
=> Fix installation path for desktop-file and icons.

src/stlink-lib/flash_loader.c
change timeout in  src/stlink-lib/flash_loader.c.   Ultimately, this is timing sensitive.  These changes improve behavior for stm32l4xx with stlinkv2-1 interfaces.
=> [regression] Changed timeout on flash write

src/common.c
=> st-flash: Fix for mmap() size_t overflow

src/stlink-lib/logging.c
FreeBSD reimplemented the libusb API, but their
implementation of libusb_set_debug() expects an
enum libusb_debug_level instead of an
enum libusb_log_level. This causes excessive
logging on FreeBSD drowning out all expected
output.
To keep the changes to other platforms minimal
the FreeBSD specific code is kept inside an
ifdef block and the enum values are recreated
as magic numbers just like the log levels for
other platforms.
=> Add support for FreeBSD's libusb reimplementation

doc/compiling.md
It's seem etc folder no longer exist, now it's on "stlink/config/udev/rules.d" instead of "stlink/etc/udev/rules.d".
=> Fixing wrong path for rules.d folder

src/stlink-lib/usb.c
The change brings the code in sync with the comment several lines above and fixes issue #1026 for me.
Please double check this! I'm not familiar with this project, and I have no idea how it could possibly work without this change.
=> Fixed reg_offset handling in stlink_usb_read_all_regs( )

src/stlink-lib/chipid.c
The FLASH_OPTR, FLASH_WRPROT1 and FLASH_WRPROT2 registers are spread across
20 option bytes.  With the original option_size of 4, only the lower 16 bits
of FLASH_OPTR could be modified.
=> Increase STM32L0 option_size to 20

doc/man/st-info.md
To show what to expect: information about the ST-link and the target.
Bumped date to this month and removed a trailing space.
Modified: doc/man/st-info.md
=> [doc] Added example for output of 'st-info --probe'

src/st-flash/flash.c
The **--connect-under-reset** option is already parsed by **src/st-flash/flash_opts.c**.  Respect this option when opening the USB connection.
=> st-flash: respect --connect-under-reset option

src/st-util/gdb-server.c
Add a special memory map for STM32H742, STM32H743/753 and STM32H750 (at least). It includes the additional SRAM regions in these chips.
Data taken from linker script generated for H750 by CubeMX software and verified against table 7 of reference manual RM0433 (except for option byte area, which is not documented):
```
MEMORY
{
DTCMRAM (xrw)      : ORIGIN = 0x20000000, LENGTH = 128K
RAM_D1 (xrw)      : ORIGIN = 0x24000000, LENGTH = 512K
RAM_D2 (xrw)      : ORIGIN = 0x30000000, LENGTH = 288K
RAM_D3 (xrw)      : ORIGIN = 0x38000000, LENGTH = 64K
ITCMRAM (xrw)      : ORIGIN = 0x00000000, LENGTH = 64K
FLASH (rx)      : ORIGIN = 0x8000000, LENGTH = 128K
}
```
=> [feature] st-util: Add specialized memory map for STM32H7 devices

CMakeLists.txt, doc/dev/developer.txt, inc/backend.h, inc/stlink.h, inc/stm32.h, src/common.c, src/st-info/info.c, src/st-util/gdb-server.c, src/stlink-lib/chipid.c, src/stlink-lib/chipid.h, src/stlink-lib/flash_loader.c, src/stlink-lib/helper.c, src/stlink-lib/helper.h, src/stlink-lib/reg.h, src/stlink-lib/usb.c, src/win32/sys_time.c, src/win32/sys_time.h
This fix improves MCU detection (specifically H7). Patch will add a check of the current MCU instructions mode and switch to thumb mode. In some cases, MCU may wrongly be in ARM instruction mode.
Optimizes MCU firmware via gdb. Adds automatic detection of cache presence and breakpoints style.
I checked this changes on the debug boards that I have (F0/F1/F3/G4). Also this branch was checked for H7 in #1059.
These changes solve the problems #1063 and #1059 (partially)
=> [feature] Improved support for STM32H7

src/common.c
The functions to properly encode and decode uint32 and uint16 relied on misguided pointer casts. this patch replaces them with clean, fast, portable code.
See https://commandcenter.blogspot.com/2012/04/byte-order-fallacy.html
=> Correctly handle endianness without reference to host platform

src/stlink-lib/flash_loader.c
Certain systems can take a while to boot and flash (because of a slow power supply or because the core is running at a lower clock speed).
Commit b8813fab9734521a1857189aab5dbf2a30d37ea4 broke st-link for several of our boards. Increasing the `WAIT_ROUNDS` define by a little fixes the issues.
This was tested on a custom board with an STM32L471 and a custom board with an STM32L496.
=> Flash_loader: increase wait rounds for slow boards

.github/ISSUE_TEMPLATE/bug-report.md
Replaced "feature request" with "bug report" in respective template.
=> [doc] Corrected spelling mistake in bug report template

doc/man/st-info.1, doc/man/st-info.md, inc/stlink.h, src/st-flash/flash.h, src/st-flash/flash_opts.c, src/st-info/info.c, src/st-trace/trace.c, src/st-util/gdb-server.c, src/stlink-lib/usb.c, src/stlink-lib/usb.h
Signed-off-by: Tarek BOCHKATI <tarek.bouchkati@gmail.com>
(Closes #417, #494)
=> Fixed old DFU serial number for STLINK programmers

src/common.c, src/stlink-lib/reg.h
The STM32H7_CORE_ID value in the manual is 0x6b00477, however it was
incorrectly set in stm32.h to 0x6b002477 - see [RM0433](https://www.st.com/content/ccc/resource/technical/document/reference_manual/group0/c9/a3/76/fa/55/46/45/fa/DM00314099/files/DM00314099.pdf/jcr:content/translations/en.DM00314099.pdf) page 3065
Fixes #1100 
Note: this has not been tested on an STM32H7 core (I don't have one)
=> Fixed STM32WB55 reading DEBUG IDCODE from the wrong address

src/st-util/gdb-server.c
Adds a description of registers for all targets (#1088). Fixes an issue with initializing memory segments. They were initializing with an incorrect pattern (#1013).
(Closes #1013, Closes #1088)
=> GDB: Fixed problems with target description

src/common.c, src/st-util/gdb-server.c, src/stlink-lib/chipid.c, src/stlink-lib/chipid.h, src/stlink-lib/flash_loader.c
Updated the device ID enum for 0x431 to "STLINK_CHIPID_STM32_F411XX" in order to cover the entire STM32F411xC/E line. Updated the chip description for the STM32F411XX to "STM32F411xC/E" and added the STM32F4 option bytes base and size. The update for option bytes fixes the "option" command. The project build was performed at command line with mingw64-build.bat. The utility st-flash.exe was tested with the evaluation board STM32F411E-DISCO:
st-flash --area=option read c:\test.bin 0x04
st-flash --area=option write 0x0FFFAAED
=> Added option byte info for STM32F411XX

src/stlink-lib/chipid.c
As per title - change description of chip id 0x0457 to L01x/L02x as per ST.
=> Updated description of chip id 0x0457 to L01x/L02x

src/common.c
Fixed a typo in the procedure of setting parameters of target.
(Closes #1146)
=> Fixed clearance of the H7 dual bank flag

src/stlink-lib/usb.c
When searching for interfaces, the libstlink is not unreferencing the probed USB devices when no STLINK programmer was found, leading to "libsub_devices were leaked" warnings, as shown below:
This warning is evidenced when using the libstlink to poll for ST-Link interfaces on Windows (I am developing an application that waits for a STLINK programmer to be connected)
A description of the problem and solution can be found here:
https://libusb-devel.narkive.com/KfZ3490q/warning-some-libusb-devices-were-leaked
=> Fix for 'libusb_devices were leaked' when no STLINK programmer was found

inc/stlink.h, src/common.c, src/st-flash/flash.c, src/st-info/info.c, src/stlink-gui/gui.c, src/stlink-lib/commands.h, src/stlink-lib/flash_loader.c, src/stlink-lib/sg.c, src/stlink-lib/usb.c
Minor connection under reset improvements. Added the halt core immediately after performing a reset.
Removed warning (about swim interface) that could mislead the user.
Added checking of the stlink commands execute status.
Added half page write fallback for stm32L0/L1.
partially closes 1098, partially closes 1138
=> Set of fixes and improvements

src/st-util/gdb-server.c
Added new memory map for STM32H72X/3X devices. Change added to allow access to internal memory that was not previously accessible with the default memory map. Tested reads of all the new memory regions on the STM32H735 Discovery board.
Fixes #1158
=> [STM32H72X/3X]: Added full access to all device memory 

src/common.c
Determination of the flash base address for the L0/L1 series is centralized in one function. Fixed get flash base address for STM32L152RE.
(Closes #1161)
=> Fixed get_stm32l0_flash_base address for STM32L152RE

src/stlink-lib/chipid.c
`stlink_chipid_get_params()` used to segfault on `memcmp()` when `struct stlink_chipid_params *params` was `NULL`. This could happen if either:
- there were no chip config files (`*.chip`), or
- `process_chipfile()` failed to parse `chip_id` from the chip config files.
The latter case is caused by the usage of `atoi()` to parse the chip id. Since the chip id is stored in hex, `atoi()` returns 0; such id cannot be matched to any actual chip.
The segfault occurs in:
https://github.com/stlink-org/stlink/blob/a52e1bc5489e23f3c1071c6912820efacaa3b22c/src/stlink-lib/chipid.c#L957
Check if `params` is `NULL`, in such case, set it to `p2`, which should not be `NULL` as long as `struct stlink_chipid_params devices[]` exists.
May fix (workaround) #1163.
=> Fixed segfault if chip was not found in chip config files

doc/devices_boards.md
Use actual [level 2 headers][headers] instead of emulating them with [bold/strong tags][bold].
[headers]: https://spec.commonmark.org/0.29/#atx-headings
[bold]: https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis
=> Use proper Markdown headers for supported MCUs

inc/stlink.h, src/stlink-lib/chipid.c
`process_chipfile()` used to improperly parse hex numbers in chip config files (`*.chip`), because it used `atoi()`, which read all such numbers as 0. This resulted, among other issues, in `chip_id` being set to 0 for all read chips. Such chip id could not match any actual MCU.
Replace the `atoi()` calls with `sscanf(…, "%i", …)`, where `%i` should match integers in base 10, 8 and 16, depending on the number prefix.
---
I can rebase this PR once (if) #1166 is merged.
=> Fixed parsing hex numbers in chip config files

src/stlink-lib/usb.c, src/stlink-lib/usb.h
Add support for ST-Link V3 devices without MSD that identify using USB PID 0x3754. This PID has been observed on a Nucleo board where MSD was disabled.
=> Added support for STLINK-V3 devices with no MSD

doc/tutorial.md
Changed an old link that 404:d and replaced it with a link that should work now instead of telling people the page doesn't exist.
Also changed the number of files to 4 since there are 4 udev rule files in the directory.
=> [doc] Corrected file path in tutorial

src/stlink-lib/chipid.c
This pull request addresses the following issues in the chipid code:
- Dumps of the `stlink_chipid_params` struct didn't include the `flash_size_reg` field.
- Comparisons between legacy hard-coded param structs and the new config files was done incorrectly and included a string pointer in the comparison. As a consequence, those comparisons always failed and incorrectly printed an error message.
- `STLINK_FLASH_TYPE_UNKNOWN` wasn't treated as a legal flash type value despite being used by `unknown_device.chip`.
N.B.: None of the chpid configs currently contain a valid `flash_size_reg` field, so comparisons will still fail after this patch.
=> Improved chipid checks and printouts

src/st-util/gdb-server.c
This is to fix issue #1196 
This has been build and tested with STM32H735 Discovery kit on the OSPI2 HyperRam
=> Updated gdb-server.c to allow external memory access on STM32H73xx

cmake/modules/Findlibusb.cmake, src/stlink-lib/libusb_settings.h
On OpenBSD libusb is provided by the libusb1 port and the existing `Findlibusb.cmake` module failed to detect it properly because it installs to `/usr/local` in accordance with the OpenBSD filesystem hierarchy. Teaching `cmake` the OpenBSD file system layout gets us half the way.
The second and last problem I've encountered is that the `MINIMAL_API_VERSION` required under OpenBSD is undeclared causing a compile error in `libusb_settings.h`. I used libusb 1.0.23p2 installed from the official binary package repository, but I don't see any reasons why OpenBSD should require a newer libusb version than other platforms.
=> Fixed compliation for OpenBSD 7.0

src/common.c
The existing includes don't pull in limits.h on FreeBSD breaking the build (on FreeBSD 13.0/amd64).
=> Included SSIZE_MAX from limits.h in src/common.c

inc/stlink.h, src/common.c, src/st-flash/flash.c, src/st-flash/flash_opts.c
Hi,
This PR is to add the possibility to only erase a section of the flash, whereas as of today it is only possible to erase the whole flash (as far as I know).
I've added this functionality in a different function, as I didn't want to mess with the parallelism in `stlink_erase_flash_mass`
Calling erase without specifying an address or size will have the same behavior as before, i.e. erasing the whole flash.
Let me know if you have any remarks.
Thanks!
=> Erase addr size / section of the flash memory with st-flash

config/chips/WLx5.chip, inc/stm32flash.h, src/option_bytes.c
This PR adds reading and writing the option bytes on the STM32WL.
=> Added writing and reading for STM32WL option bytes

src/st-info/info.c, src/stlink-lib/chipid.c
Hi everyone,
during my work i made some changes to the stlink library which i thought of would benefit the overall project.
These changes include optimizations in the processing of chipfiles and in a seperate PR the addition of option byte descriptions.
=> Optimisation for processing chipid files

config/chips/F401xD_xE.chip
Hi everyone,
heres the PR i was talking about in #1234.
It simply adds the option byte base address for STM32F401VDT and other STM32F401xD devices.
=> Added parametres option_base, option_size for F401xD_xE

config/chips/F1xx_XLD.chip, doc/devices_boards.md, src/flashloader.c
This PR defines the `option_base` and `option_size` for F1xx_XLD which so far seems to be just used by GD32F30x chips which use the same option bytes configuration as STM32F1.
I also included the chip I've been using in `devices_boards.md`, it's pretty much the same as the existing GD32F303VGT6 chip mentioned there, mainly just a smaller package type.
=> Added support for option bytes to F1xx_XLD (GD32F30x)

src/st-trace/trace.c
Fixed register read to use the right register for TPI_ACPR.
Updating to expect frequency units for clock and trace flags.
Making sure trace frequency is not less than 1/5 of the system frequency.
=> [st-trace] clock issues

doc/compiling.md
This is required to get the `chips` directory in place. References #1237.
=> [doc] Added `make install` to the macOS compiling instructions

src/common_flash.c
Currently L152RE isn't covered by case in *get_stm32l0_flash_base* (*common_flash.c*) and consequently `STM32L0_FLASH_REGS_ADDR` is returned instead of `STM32L_FLASH_REGS_ADDR`.
This PR fix again this issue.
First fix was 2a3c57747fd0caefca37f81f55be43ad175ffa2d
but lost during merge (dc5388d94c959b271d51cd98ea973cf4e8febcf0)
=> Fixed flash regs addr for STM32L152RET6 in common_flash.c

CMakeLists.txt, README.md
=> [compilation] Corrected path to stlink/chips subdirectory

config/udev/rules.d/49-stlinkv3.rules
Adds udev rule for the [stlink V3 MINIE programmer](https://www.st.com/en/development-tools/stlink-v3minie.html)
=> Added udev-rule rule for the V3 MINIE programmer

src/stlink-gui/gui.c
Explicitely convert from goffset to gsize with prior overflow
check. Implicit conversion is forbidden by compiler settings.
=> [compilation] Fixed GUI compilation failure on OpenBSD i386

doc/devices_boards.md
Maintain the documentation with a new device ID found for device GD32F303VET6
=> [doc] Added device ID for GD32F303VET6

src/st-trace/trace.c
This should fix issue #1272.
The windows signal handling was returning FALSE which caused the default handler to be called.  The default handler called ExitProcess before our process had a chance to cleanup.  While the code looks similar, st-util does not have the same issue since it actually cleans up its resources in the signal handler.
=> Fixed st-trace reconnect on Windows

doc/tutorial.md
Udev rules link pointed to [/etc/udev/rules.d](https://github.com/stlink-org/stlink/tree/master/etc/udev/rules.d), which doesn't exist *anymore*.
Replaced the link by the correct [/config/udev/rules.d](https://github.com/stlink-org/stlink/tree/master/config/udev/rules.d) and respecting Markdown link formatting (no bare URLs).
=> Fix broken doc link

src/st-util/gdb-server.c, src/stlink-lib/chipid.c
Format string "%s" that does not control the length of data written may overflow.
=> Fixed unbounded write and check return values of sscanf

src/st-trace/trace.c
Pass a null pointer to "%s" is undefined behaviour.
=> Added null check for return value of stlink_chipid_get_params()

cmake/modules/Findlibusb.cmake, cmake/modules/get_version.cmake
according to https://cmake.org/cmake/help/v3.10/command/if.html#command:if
else() should have the same expression as if()
but elseif() can contain different expression
=> Fixed warning in a few *.cmake files

CMakeLists.txt, src/stlink-gui/CMakeLists.txt
Instead of defining own CMAKE_INSTALL_SHAREDIR, use existing CMAKE_INSTALL_FULL_DATADIR.
This way, CMAKE_INSTALL_PREFIX is respected.
=> CMake: Avoid hard-wired /usr/local/share

src/stlink-lib/sg.c
Otherwise 0 is printed as 0.
```
// works
printf("Command 0x%02x \n", 0x0);
// broken for 0
printf("Command %#02x \n", 0x0);
printf("Command %#02x \n", 0x00);
printf("Command %#02x \n", 0xFF);
```
https://godbolt.org/z/roGYqde3a
=> Fix printf format to print 0 correctly

src/stlink-lib/usb.c
I happen to have a stm32f4discovery board with an integrated STLink-V2 which cannot read the target voltage (should be around 3V). The cause for this issue appears to be a broken ADC in the STLink STM32F103 chip. Otherwise the STLink USB interface works, and the STM32CubeProgrammer software provided by ST manages to perform flash writing operations just fine even though it shows a target voltage of zero.
However, when attempting to flash the board with st-flash, as soon as flash erase completes, the tool crashes with a floating point exception in `_stlink_usb_target_voltage()`, as the `GET_TARGET_VOLTAGE` command returns an all-zero response, and as a result `2400 * reading \ factor` is a division by zero.
This pull request adds a check for `factor==0` or `reading==0`, and in that case …
=> Do not crash when the STLink chip returns a voltage factor of zero.

config/chips/U535_U545.chip, config/chips/U55Fx_U5Gx.chip, config/chips/U575_U585.chip, config/chips/U59x_U5Ax.chip, inc/stm32.h, src/stlink-lib/common_flash.c
I have been using the stm32U535 and I was getting an error when trying to write or erase parts of the flash with the st-flash.exe program. Analyzing the code I noticed that:
1) There was only support for chip ID 0x482. I added the others with the appropriate flash/ram specs.
0x455: STM32U535/545
0x476: STM32U5Fx/5Gx
0x481: STM32U59x/5Ax
0x482: STM32U575/585
2) It was not possible to delete a page from the flash because the original test was based only on the STM32L5x2xx (with one or two banks and 2k pages) while the U5 family has 8k pages and two banks.
As this is my first contribution I'm not sure if the way I solved the problems was the best. I remain at your disposal for further clarification.
=> Fixed support for STM32U5 chips
