stlink-org/stlink

src/stlink-common.c, src/stlink-common.h
I added support for flashing STM32F04X series microcontrollers. Tested with stlinkv2 and it works for me.
=> Added support for flashing STM32F042

src/stlink-common.c, src/stlink-common.h
Signed-off-by: giuseppe barba <giuseppe.barba@gmail.com>
=> Added support for flashing STM32F091

gdbserver/gdb-server.c
This enables GCC to only erase needed pages.
=> Fix F2 memory map

src/stlink-common.h, src/stlink-usb.c
Reverts texane/stlink#328
Lets investigate this more
=> Revert "Make _stlink_usb_reset use hardreset"

configure.ac
=> correct error message is given upon missing pkg-config package. 

src/st-term.c
Implemented non-blocking ring buffer for st-term. Tested on STM32F407 discovery board.
For device side communication I will create pull request in nekromant/antares.
=> Implement simple non-blocking ring buffer for communication over stlink

CMakeLists.txt
Minor fix to listfile: test for MINGW shouldn't expand the variable.
=> Cmake build

gdbserver/gdb-server.c
This patch handles the cache on the cortex-m7 stm32f7 cpu.
When gdb inserts a soft breakpoint (which is the default for
code in RAM), it replaces an instruction with a breakpoint
instruction.  But if the caches are enabled, the replacement
may be made only in the D-cache.  To reach the I-cache, the
D-cache must be flushed and the I-cache invalidated.
This implementation is coarse: it cleans the whole D-cache
and invalidate the whole I-cache.  It is possible to
track which cache lines have to be cleaned and invalidated.
=> st-util: synchronize cache for stm32f7

gdbserver/gdb-server.c
Signed-off-by: Greg Meiste <w30289@motorola.com>
=> Add memory map for STM32L4

src/stlink-usb.c
Add some better sanity checking when using libusb_open and cleanup accordingly.
Fixes hang (tested on debian 8, amd64, libusb 1.0.19):
libusb: warning [add_to_flying_list] failed to arm first timerfd (errno 9)
libusb: warning [libusb_close] internal signalling write failed, closing anyway
=> st-probe: Fix hang when user has no libusb access

README, src/st-info.c, src/stlink-usb.c
Initial work on OpenOCD hla serial info, which is a followup of work not done in PR  https://github.com/texane/stlink/pull/391#issuecomment-206467687
This also fixes the link/build image of the README.md to texane/stlink. Please would you enable the build and add support for building pull requests under Travis ?
=> st-info: Add support for OpenOCD hla_serial printing

src/st-info.c, src/stlink-usb.c
=> st-info: --probe: Due to already claimed stlink one of them was zero

src/tools/gui/stlink-gui.c
=> stlink_gui: Fix compiler warning on overflow

CMakeLists.txt, include/stlink.h, include/stlink/backend.h, include/stlink/sg.h, src/common.c, src/flash_loader.c, src/gdbserver/gdb-remote.c, src/gdbserver/gdb-server.c, src/sg.c, src/tools/flash.c, src/tools/gui/stlink-gui.c, src/tools/term.c, src/usb.c, tests/usb.c
Trying to fix all warnings noticed by #402 for the different builds:
=> WIP: Fix compiler warnings

src/gdbserver/gdb-server.c
It improves readability and will allow parsing of more complex monitor
commands.
=> Unhexify GDB monitor commands (qRcmd)

CMakeLists.txt
Signed-off-by: Andrew Andrianov <andrew@ncrmnt.org>
=> CMakeLists.txt: Fix linker command in generated .pc file

src/mingw/mingw.c, src/mingw/mingw.h
Sorry, I made silly a copypaste error in a previous pull request.
=> use correct macros for switch usleep realisation

debian/changelog
libstlink.so is 1.4.0 but debian package version still 1.2.0
=> update debian package version

src/tools/gui/stlink-gui.c
=> try to fix #666 issue

src/flash_loader.c
Fix for the problem I was experiencing in #654.
=> Fix missing flash_loader for L011

src/common.c
This patch adds support for mass erasing the second bank on STM32F10x_XL!
Issue no: 767
=> Add support for mass erasing second bank on STM32F10x_XL (#767)

README.md
See https://github.com/texane/stlink/issues/774
=> Added howto for sending NRST signal through GDB

README.md
Add stlink-tools link for Debian and Ubuntu
=> Add stlink-tools link for Debian and Ubuntu

src/usb.c
=> Added more error info to WLOGs during probe.

Makefile
=> Add CMAKEFLAGS and install target

src/common.c
Fixes https://github.com/stlink-org/stlink/issues/663
=> Enhanced output for error msg "addr not a multiple of pagesize, not supported"

README.md
=> Fix: tutorial.md should be correctly linked from readme

src/stlink-lib/flash_loader.c
=> Use vl flashloader for all STMF1 series

src/st-trace/trace.c, src/stlink-lib/helper.c, src/stlink-lib/usb.c
This pull request combines @Ant-On's fix #1076 as well as fixes for two new clang bugs introduced in #1072.
=> Bugfixes for compilation with clang

src/stlink-lib/usb.c
Correction of the regression that occurred while implementing the STLINK/V3 support.
(Fixes  #1045)
=> Fixed support for STLINK/V1 programmer

src/stlink-lib/usb.c
=> Removed limit check for WRITEMEM_32BIT

src/st-util/gdb-server.c
=> Fixed notification "unknown option -- u" in tool st-util
